/** @type {import('tailwindcss').Config} */
const path = require("path");

module.exports = {
  content: [
    path.join(__dirname, "./app/**/*.{js,ts,jsx,tsx,mdx}"),
    path.join(__dirname, "./pages/**/*.{js,ts,jsx,tsx,mdx}"),
    path.join(__dirname, "./components/**/*.{js,ts,jsx,tsx,mdx}"),
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
        display: ["var(--font-outfit)", "sans-serif"],
      },
      colors: {
        background: "var(--md-sys-color-surface)",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "var(--md-sys-color-surface-container)",
          foreground: "hsl(var(--card-foreground))",
        },
        primary: {
          DEFAULT: "var(--md-sys-color-primary)",
          foreground: "var(--md-sys-color-on-primary)",
        },
        secondary: {
          DEFAULT: "var(--md-sys-color-secondary)",
          foreground: "var(--md-sys-color-on-primary)",
        },
        accent: {
          DEFAULT: "var(--md-sys-color-primary-container)",
          foreground: "var(--md-sys-color-primary)",
        },
        muted: {
          DEFAULT: "var(--md-sys-color-outline)",
          foreground: "#8E9199",
        },
        border: "var(--md-sys-color-outline)",
        input: "var(--md-sys-color-outline)",
        ring: "var(--md-sys-color-primary)",
        m3: {
          primary: "var(--md-sys-color-primary)",
          "on-primary": "var(--md-sys-color-on-primary)",
          "primary-container": "var(--md-sys-color-primary-container)",
          surface: "var(--md-sys-color-surface)",
          "surface-container": "var(--md-sys-color-surface-container)",
          "surface-container-high": "var(--md-sys-color-surface-container-high)",
          outline: "var(--md-sys-color-outline)",
          secondary: "var(--md-sys-color-secondary)",
        },
        purple: {
          50: "#faf5ff",
          100: "#f3e8ff",
          200: "#e9d5ff",
          300: "#d8b4fe",
          400: "var(--md-sys-color-primary)",
          500: "var(--md-sys-color-primary)",
          600: "var(--md-sys-color-primary)",
          700: "var(--md-sys-color-primary)",
          800: "var(--md-sys-color-primary)",
          900: "rgba(168, 199, 250, 0.3)",
          950: "rgba(168, 199, 250, 0.1)",
        },
        indigo: {
          50: "#eef2ff",
          100: "#e0e7ff",
          200: "#c7d2fe",
          300: "#a5b4fc",
          400: "var(--md-sys-color-primary)",
          500: "var(--md-sys-color-primary)",
          600: "var(--md-sys-color-primary)",
          700: "var(--md-sys-color-primary)",
          800: "var(--md-sys-color-primary)",
          900: "rgba(168, 199, 250, 0.3)",
          950: "rgba(168, 199, 250, 0.1)",
        },
        slate: {
          50: "#fafaf9",
          100: "#f5f5f4",
          200: "#e7e5e4",
          300: "#d6d3d1",
          350: "#b5b2b0",
          400: "#a8a29e",
          500: "#78716c",
          600: "#57534e",
          700: "var(--md-sys-color-outline)",
          800: "var(--md-sys-color-outline)",
          850: "var(--md-sys-color-outline)",
          900: "var(--md-sys-color-surface-container)",
          950: "var(--md-sys-color-surface)",
        },
        emerald: {
          50: "#ecfdf5",
          100: "#d1fae5",
          200: "#a7f3d0",
          300: "#6ee7b7",
          400: "var(--md-sys-color-secondary)",
          500: "var(--md-sys-color-secondary)",
          600: "var(--md-sys-color-secondary)",
          700: "var(--md-sys-color-secondary)",
          800: "var(--md-sys-color-secondary)",
          900: "rgba(196, 231, 203, 0.3)",
          950: "rgba(196, 231, 203, 0.1)",
        },
      },
    },
  },
  plugins: [],
}
